### ISSUE TITLE
`suspense: true`일 때 useQuery의 타입이 (`TData | undefined`)로 타입이 불일치하는 현상

### ISSUE THREAD

**Issue by thyeone** [crescenders/crescendo-frontend#98]
## 🚅 Issue 한 줄 요약
`suspense: true`일 때 useQuery의 타입 불일치 (`TData | undefined`) 현상

## 문제 상황
Suspense를 사용하기 위해 ToDoList 컴포넌트를 Suspense로 감쌌습니다.

``` tsx
const App = () => {
  return (
    <>
      <h1>To-Do List</h1>
      <Suspense fallback{<div>Loading ...</div>}>
        <ToDoList />
      </Suspense>
    </>
  );
};
```

``` tsx
const ToDoList = () => {
  const { data } = useGetTodo(); // Todo[] | undefined
  
  return (
    <ul>
      {data.map((todo) => (
        <li key={todo.id}>{todo.content}</li> // data는 undefined 일 수 있기 때문에 에러 발생
      ))}
    </ul>
  );
};
```
Suspense로 감쌌기 때문에 `data`는 항상 성공해야 할 것입니다. ToDoList의 Promise가 Pendeing일 때는 로더가 보이고 fulfilled라면 ToDoList를 렌더링하기때문입니다.
하지만 data의 타입은 `Todo[] | undefined`로 평가됩니다.

### 해결 방법
1. 옵셔널 체이닝을 사용한다.
``` tsx
const ToDoList = () => {
  const { data } = useGetTodo();

  return (
    <ul>
      {data?.map((todo) => (
        <li key={todo.id}>{todo.content}</li>
      ))}
    </ul>
  );
};

```
2. 타입 좁히기
```tsx
const ToDoList = () => {
  const { data } = useGetTodo();

  if (!data) return null;

  return (
    <ul>
      {data.map((todo) => (
        <li key={todo.id}>{todo.content}</li>
      ))}
    </ul>
  );
};

```

3. useQuery 커스텀 훅 내부에서 TypeScript의 `NonNullable` 유틸리티 타입을 사용한 값을 반환한다.

따라서 위와 같이 data가 undefined일 상황을 고려한 코드를 작성해야하기 때문에, 번거로워지고 코드도 지저분해집니다.
하단의 방법을 통해 문제를 해결한다면 데이터 페칭이 성공한 상태에만 집중하면서 코드를 보다 깔끔하게 처리할 수 있습니다.
## 해당 문제를 해결할 수 있는 방법
1. Toss/slash 라이브러리 [useSuspensedQuery](https://slash.page/ko/libraries/react/react-query/src/hooks/usesuspendedquery.i18n/) 사용

2. [tanstack/query v5](https://tanstack.com/query/v5/docs/react/guides/migrating-to-v5) 가 제공하는 `useSuspenseQuery`, `useSuspenseInfiniteQuery` 사용

1번은 마이그레이션이 아닌 해당 문제를 극복하기 위한 라이브러리를 사용하기 때문에, 변경점이 그리 많지 않은 것이 장점이지만 `useSuspenseInfiniteQuery`를 사용할 수 없습니다. (하지만 위에서 언급한 `NonNullable`를 통해 해결 가능)

2번은 v5에서 변경점이 꽤 많기 때문에 작업자가 이를 숙지해야 하는 것이 단점이라고 생각합니다.

### 연관 레퍼런스
- https://github.com/TanStack/query/issues/1297

**Comment by overtae** [comment]
깔끔한 정리 감사합니다! `NonNullable`이란 타입이 있었군요.. 링크해두신 자료들을 살펴보니 useSuspensedQuery의 형태가 v5랑 비슷한 것 같아서 차라리 v5로 마이그레이션하는 게 낫지 않을까 하는 생각이 듭니다..!
